### ISSUE TITLE
Lock to Jekyll 3.9

### ISSUE THREAD

**Issue by MichaelCurrin** [Kingfish404/pure-blog#1]
For someone using this template on GH Pages, they would get inconsistent results when installing locally.

The Gemfile does not lock Jekyll to 3 but you end up with Jekyll 4.

So I recommend this

https://github.com/MichaelCurrin/jekyll-blog-demo/blob/master/Gemfile#L3-L4

Note Kramdown parser is essential or you'll get an error on serving in 3.9

**Comment by Kingfish404** [comment]
Thanks, and it will be fix in next commit
