### ISSUE TITLE
Refactor post list

### ISSUE THREAD

**Issue by MichaelCurrin** [Kingfish404/pure-blog#4]
On index.html

Instead of

```html
{% for post in site.posts %}

    {% if forloop.index > site.post_num_index %}
    {% continue %}
```

It would be more Jekyll convention to use limit instead .

```html
{% assign posts = site.posts | limit: site.post_num_index %}
{% for post in posts %}
...
```

Also better naming would be

```
site.max posts
```

**Comment by MichaelCurrin** [comment]
By the way, `continue` skips the current iteration only so it has to skip a lot which is inefficient 

- 1
- 2
- 3
- 4 skip
- 5 skip
- ...
- 99 skip
- 100 skip
- stop 

But if you `break`, it would stop iterating

- 1
- 2
- 3
- stop

**Comment by Kingfish404** [comment]
Thank you very much for your suggestion. This is indeed an obvious logical problem. I will fix this problem in the next submission.

By the way, I don’t know why
```liquid
{% assign posts = site.posts | limit: site.post_num_index %}
{% for post in posts %}
...
```
not working.

I replaced it with the scheme below 

```liquid
{% for post in site.posts limit: site.max_posts %}
...
```

**Comment by MichaelCurrin** [comment]
Oh sorry `limit` is not a filter like I thought, just a for loop modifier.

I checked this as a reference now https://learn.cloudcannon.com/jekyll-cheat-sheet/
